function [finalVolume,finalmAb_ext,finalmAb_mass] = printFinalmAb(Info)

finalVolume = Info.Xopt(end,1);
finalmAb_ext = Info.Xopt(end,8);
finalmAb_mass = Info.Xopt(end,8)*Info.Xopt(end,1);

fprintf( ...
            [ ...
                'Final liquid volume: %g L\n' ...
                'Final mAb conc: %g mg/L\n' ...
                'Final mAb amount: %g mg\n' ...
            ], ...
            finalVolume, ...
            finalmAb_ext, ...
            finalmAb_mass ...
       );
end